server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exh_my_blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Exh125874
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
    hikari.idle-timeout: 30000
    hikari.pool-name: hikariCP
    hikari.max-lifetime: 30000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1

  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.exh.myblog.model
  mapper-locations: classpath:/mapper/*.xml